[package]
name = "asahi-battery-threshold"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
dirs = "4.0.0"
env_logger = "0.10.0"
log = "0.4.17"
serde = "1.0.150"
serde_derive = "1.0.150"
thiserror = "1.0.37"
toml = "0.5.10"
